spring:
  application:
    name: DigiJed

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:169572712836-0iniu2dh6p320qsj4ac9pjmoi0gflrip.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope:
              - email
              - profile
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email

app:
  jwt:
    secret: ${JWT_SECRET:f8K97xIjL8wzQ6KpM9DcJx8u5V3Kw0LV0j9yxP9oeWk=}
    expiration-ms: 3600000  #1 hour

logging:
  config: classpath:logback-spring.xml